# This is used for local development
# syntax=docker.io/docker/dockerfile:1.10.0
services:
  postgresql:
    image: postgres:16.4
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring_test_db
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - spring-test-network
    ports:
      - "5432:5432"

networks:
  spring-test-network:
    driver: bridge
    name: spring-test-network
